### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by fatmcgav** [sensu-plugins/sensu-plugins-couchdb#6]
Any chance of a new release which includes 'check-couchdb-alive'?

**Comment by majormoses** [comment]
@fatmcgav yes, we are working on formalizing this as maintainers, it should never happen. In the meantime please ping me as well as the maintainer that released the change if there is ever a functional change that has been merged and not released in 24 hours so I can release and have a discussion with them about it.

**Comment by fatmcgav** [comment]
@majormoses Cheers for that.

**Comment by majormoses** [comment]
if you would like to hear more about some our current initiatives and how you can get involved you should check out: https://blog.sensuapp.org/community-maintenance-mode-d109e75bcbc4 and fill out the survey.

**Comment by majormoses** [comment]
I am gonna release a 1.0.0 version of this gem as afterwards I am gonna probably do some of the work on prepping it for ruby 2.4 and sensu 0.29 && 1.0 (crazy huh?) and I have not figured out how many breaking releases we will need for this gem but I wanted to ensure that you are not left broken until you are ready to upgrade your sensu setup.

**Comment by majormoses** [comment]
glad I did, we will drop ruby 1.x support in 2.x

**Comment by majormoses** [comment]
I am aware that the current builds are broken and you will be unlikely to use the intermediary releases from rubygems.org because I want to just take a big cleaning sweep to this repo, I have released it and will attach the .gem file to the release so it can be easier on you if you need it.

**Comment by majormoses** [comment]
released: https://github.com/sensu-plugins/sensu-plugins-couchdb/releases/tag/1.0.0
gem directly: https://github.com/sensu-plugins/sensu-plugins-couchdb/releases/download/1.0.0/sensu-plugins-couchdb-1.0.0.gem
